server:
  port: 8520

spring:
  datasource: # 数据库配置
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/font?useUnicode=true&characterEncoding=utf8
    username: root
    password: lm13190492195
    # password: DB_mima~9749
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.ym.163.com
    port: 25
    username: cxlm@cxlm.work
    password: cxlmmima123456
    from: "MyFont 后台管理"