logging:
  level:
    work.cxlm: INFO
  file:
    path: ${user.home}/key3-prod/logs

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:6621/key3?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=UTC
    username: cxlm
    password: DB_mima~9749
  jpa:
    show-sql: false

key3:
  doc-disabled: false
  production-env: true
  mode: production
  workDir: ${user.home}/key3-prod/
  cache: level

redis:
  default-name: single
  clients:
    single:  # 单点集群
      mode: SINGLE
      address: redis://127.0.0.1:6543
      password: REDIS_mima~9749
      database: 0
      codec-bean-name: jsonJacksonCodec
      min-idle: 10
      max-active: 100
      max-idle-timeout: 1800_000   #最大空闲时间

# jedis配置，为了兼容redisLock
jedis:
  timeout: 1000
  pool:
    max-total: 200
    max-wait-millis: 2000
    max-idle: 100
    min-idle: 10
    min-evictable-idle-time-millis: 1800000
  master-s1:
    host: 127.0.0.1
    port: 6543
    name: master-s1
    password: REDIS_mima~9749
  slave-s1:
    host: 127.0.0.1
    port: 6543
    name: slave-s1
    password: REDIS_mima~9749