server:
  port: 8520

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource: # 数据库配置
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/key3?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=UTC
    username: root
    password: DB_mima~9749
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  profiles:
    active: dev
#  mail:
#    host: smtp.ym.163.com
#    port: 465
#    username: cxlm@cxlm.work
#    password: "**************"
#    from: "MyFont 后台管理"

my-font:
#  download-timeout: 5m
  cache: level
  version: @app_version@